# Variable 'LT_ACCESSKEY' was defined in the Variables tab
# Variable 'LT_USERNAME' was defined in the Variables tab
# Variable 'MAILSLURP_KEY' was defined in the Variables tab
# Variable 'TEST_FILTER' was defined in the Variables tab
# Variable 'TWILIO_ACCOUNT_SID' was defined in the Variables tab
# Variable 'TWILIO_AUTH_TOKEN' was defined in the Variables tab
variables:
- name: BuildParameters.TestProjects
  value: '**/*[Tt]ests/*.csproj'
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: NUTEST
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 8.0.401
    inputs:
      version: 8.0.401
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: '**\*.csproj'
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Test
    condition: succeededOrFailed()
    inputs:
      command: test
      projects: $(BuildParameters.TestProjects)
      arguments: --configuration $(BuildConfiguration) --no-build --no-restore --logger trx  --filter="$(TEST_FILTER)" --logger:ReportPortal
      testRunTitle: Polaris System Tests
  - task: qameta.allure-azure-pipelines.PublishAllureReport.PublishAllureReport@1
    displayName: Publish Allure Report
    condition: succeededOrFailed()
    inputs:
      allureVersion: 2.30.0
      testResultsDir: $(Build.SourcesDirectory)\DemoSystemTests\bin\$(BuildConfiguration)\net8.0\allure-results
      reportName: test-report
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    enabled: False
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...
