namespace PolarisLite.Web.Plugins.Performance;
public static class PerformanceMetrics
{
    public const string Timestamp = "Timestamp";
    public const string AudioHandlers = "AudioHandlers";
    public const string AudioWorkletProcessors = "AudioWorkletProcessors";
    public const string Documents = "Documents";
    public const string Frames = "Frames";
    public const string JSEventListeners = "JSEventListeners";
    public const string LayoutObjects = "LayoutObjects";
    public const string MediaKeySessions = "MediaKeySessions";
    public const string MediaKeys = "MediaKeys";
    public const string Nodes = "Nodes";
    public const string Resources = "Resources";
    public const string ContextLifecycleStateObservers = "ContextLifecycleStateObservers";
    public const string V8PerContextDatas = "V8PerContextDatas";
    public const string WorkerGlobalScopes = "WorkerGlobalScopes";
    public const string UACSSResources = "UACSSResources";
    public const string RTCPeerConnections = "RTCPeerConnections";
    public const string ResourceFetchers = "ResourceFetchers";
    public const string AdSubframes = "AdSubframes";
    public const string DetachedScriptStates = "DetachedScriptStates";
    public const string ArrayBufferContents = "ArrayBufferContents";
    public const string LayoutCount = "LayoutCount";
    public const string RecalcStyleCount = "RecalcStyleCount";
    public const string LayoutDuration = "LayoutDuration";
    public const string RecalcStyleDuration = "RecalcStyleDuration";
    public const string DevToolsCommandDuration = "DevToolsCommandDuration";
    public const string ScriptDuration = "ScriptDuration";
    public const string V8CompileDuration = "V8CompileDuration";
    public const string TaskDuration = "TaskDuration";
    public const string TaskOtherDuration = "TaskOtherDuration";
    public const string ThreadTime = "ThreadTime";
    public const string ProcessTime = "ProcessTime";
    public const string JSHeapUsedSize = "JSHeapUsedSize";
    public const string JSHeapTotalSize = "JSHeapTotalSize";
    public const string FirstMeaningfulPaint = "FirstMeaningfulPaint";
    public const string DomContentLoaded = "DomContentLoaded";
    public const string NavigationStart = "NavigationStart";
}
