global using System;
global using NUnit.Framework;
global using OpenQA.Selenium;
global using System.Drawing;
global using System.IO;
global using System.Collections.Generic;
global using OpenQA.Selenium.Interactions;
global using OpenQA.Selenium.Support.UI;
global using SeleniumExtras.WaitHelpers;

global using OpenQA.Selenium.Appium;
global using OpenQA.Selenium.Appium.Android;
global using OpenQA.Selenium.Appium.Enums;
global using OpenQA.Selenium.Appium.Service;
global using OpenQA.Selenium.Appium.Service.Options;
global using OpenQA.Selenium.Appium.MultiTouch;
global using OpenQA.Selenium.Appium.Interfaces;
global using PolarisLite.Core.Layout;
global using PolarisLite.Logging;